security:
    # access_denied_url: /admin
    encoders:
        App\Entity\User:
            algorithm: bcrypt
    providers:
        in_database: 
            entity:
                class: App\Entity\User
                property: username
        # used to reload user from session & other features (e.g. switch_user)
       
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true

            provider: in_database
           
            form_login:
                login_path: security_login
                check_path: security_login
                default_target_path: admin.property.index
            
            
            logout:
                path:   /logout
                target: /
            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

           
                
                
            # guard:
            #   authenticators:
            #          - App\Security\LoginFormAuthenticator
            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # matches /admin/users/*
        # - { path: ^/admin/users, roles: ROLE_SUPER_ADMIN }

        # matches /admin/* except for anything matching the above rule
        # - { path: ^/admin, roles: ROLE_ADMIN }
        #  - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/profile, roles: ROLE_USER }
    

