# user:
#    path: /admin/user
#    controller: App\Controller\Admin\AdminUserController::index


# edit:
#   path: /admin/property
#   controller: App\Controller\Admin\AdminPropertyController::edit

logout:
    path: /logout

